name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:
  build-macos:
    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.14
      OSX_MIN_VERSION: 10.14
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: install dependencies
      run: brew install hidapi zmq libpgm miniupnpc ldns expat libunwind-headers protobuf
    - name: build boost
      run: |
        wget https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.gz
        tar -xzf boost_1_71_0.tar.gz
        cd boost_1_71_0
        ./bootstrap.sh 
        ./b2
        ./b2 install
    - name: build
      run: |
        ./build-haven.sh release-static-mac-x86_64 -j${nproc}
        chmod +x monero/build/release/bin/*
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Haven-MacOS-10.14-and-later
        path: monero/build/release/bin/
